In [1]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np


In [10]:
# Load the image
image_path = "C:/Users/hp/pred/pred9.jpg"
image = cv2.imread(image_path)

In [11]:
# Preprocess the image
image = cv2.resize(image, (200, 200)) # resize the image to the input size of the model
image = image / 255.0 # normalize the pixel values to the range [0, 1]
image = np.expand_dims(image, axis=0) # add a batch dimension
img = np.array(image)
print(image)

[[[[0.01176471 0.01176471 0.01176471]
   [0.00784314 0.00784314 0.00784314]
   [0.01960784 0.01960784 0.01960784]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00784314 0.00784314 0.00784314]
   [0.01568627 0.01568627 0.01568627]
   [0.01176471 0.01176471 0.01176471]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.         0.         0.        ]
   [0.00784314 0.00784314 0.00784314]
   [0.01176471 0.01176471 0.01176471]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  ...

  [[0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   ...
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]
   [0.00392157 0.00392157 0.00392157]]

  [[0.00392157 0.00392157 0.00392157]
   [0.0

In [12]:
# Load the trained model
model = load_model("BrainTumorDetection.h5")

In [13]:
# Predict the output
output = model.predict(image)

# Return a text based on the prediction
#"output[0][0]" refers to the first element of the first row of the output array returned by the model's "predict" method.

if output[0][0] < 0.5:
    text = "The brain does not have a tumor"
else:
    text = "The brain has a tumor"

    
# Show the image

cv2.imshow("Input Image", cv2.resize(cv2.imread(image_path), (600, 600)))
cv2.waitKey(0)
cv2.destroyAllWindows()

print(output)
print(text)

1/1 [==============================] - 1s 573ms/step
[[1.]]
The brain has a tumor
